language: python
sudo: false
python: 3.5
install: "pip install pytest tox"
env:
    - TOX_ENV=py27
    - TOX_ENV=py33
    - TOX_ENV=py34
    - TOX_ENV=py35
    - TOX_ENV=pypy
script:
    - tox -e $TOX_ENV
